# Generated by Django 2.1.4 on 2018-12-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField()),
                ('short_url', models.CharField(max_length=64)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
